cookietemple_version: '1.3.2 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: sc-toolbox
project_slug_no_hyphen: sc_toolbox
template_version: '2.0.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: schillerlab
creator_github_username: zethson
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: schillerlab
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: sc-toolbox
project_short_description: A collection of project templates and useful code snippets
  for single-cell data analysis with Scanpy.
version: 0.12.1
license: MIT
